config/routes.rb
Sam::Application.routes.draw do
  
	resources :clubs, :shallow => true do
	    collection do 
	      get :top
	    end 
	end  

end

app/models/club.rb
class Club < ActiveRecord::Base
  attr_accessible :exclusive, :name
end

app/models/high_score.rb
class HighScore < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  # GET /clubs
  # GET /clubs.json
  def index
    @clubs = Club.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clubs }
    end
  end

  # GET /clubs/1
  # GET /clubs/1.json
  def show
    @club = Club.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @club }
    end
  end

  def top
     puts 'KKKKKKK'
  end 

  # GET /clubs/new
  # GET /clubs/new.json
  def new
    @club = Club.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @club }
    end
  end

  # GET /clubs/1/edit
  def edit
    @club = Club.find(params[:id])
  end

  # POST /clubs
  # POST /clubs.json
  def create
    @club = Club.new(params[:club])

    respond_to do |format|
      if @club.save
        format.html { redirect_to @club, notice: 'Club was successfully created.' }
        format.json { render json: @club, status: :created, location: @club }
      else
        format.html { render action: "new" }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clubs/1
  # PUT /clubs/1.json
  def update
    @club = Club.find(params[:id])

    respond_to do |format|
      if @club.update_attributes(params[:club])
        format.html { redirect_to @club, notice: 'Club was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clubs/1
  # DELETE /clubs/1.json
  def destroy
    @club = Club.find(params[:id])
    @club.destroy

    respond_to do |format|
      format.html { redirect_to clubs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/high_scores_helper.rb
module HighScoresHelper
end

app/views/clubs/_form.html.erb
<%= form_for(@club) do |f| %>
  <% if @club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@club.errors.count, "error") %> prohibited this club from being saved:</h2>

      <ul>
      <% @club.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :exclusive %><br />
    <%= f.check_box :exclusive %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clubs/edit.html.erb
<h1>Editing club</h1>

<%= render 'form' %>

<%= link_to 'Show', @club %> |
<%= link_to 'Back', clubs_path %>

app/views/clubs/index.html.erb
<h1>Listing clubs</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Exclusive</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clubs.each do |club| %>
  <tr>
    <td><%= club.name %></td>
    <td><%= club.exclusive %></td>
    <td><%= link_to 'Show', club %></td>
    <td><%= link_to 'Edit', edit_club_path(club) %></td>
    <td><%= link_to 'Destroy', club, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Club', new_club_path %>

<div id ="disqus_thread">
<%= raw disqus_thread %>
</div>

app/views/clubs/new.html.erb
<h1>New club</h1>

<%= render 'form' %>

<%= link_to 'Back', clubs_path %>

app/views/clubs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @club.name %>
</p>

<p>
  <b>Exclusive:</b>
  <%= @club.exclusive %>
</p>


<%= link_to 'Edit', edit_club_path(@club) %> |
<%= link_to 'Back', clubs_path %>

<div id ="disqus_thread">
  <%= raw disqus_thread %>
</div>

app/views/high_scores/_form.html.erb
<%= form_for(@high_score) do |f| %>
  <% if @high_score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@high_score.errors.count, "error") %> prohibited this high_score from being saved:</h2>

      <ul>
      <% @high_score.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/high_scores/edit.html.erb
<h1>Editing high_score</h1>

<%= render 'form' %>

<%= link_to 'Show', @high_score %> |
<%= link_to 'Back', high_scores_path %>

app/views/high_scores/index.html.erb
<h1>Listing high_scores</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @high_scores.each do |high_score| %>
  <tr>
    <td><%= link_to 'Show', high_score %></td>
    <td><%= link_to 'Edit', edit_high_score_path(high_score) %></td>
    <td><%= link_to 'Destroy', high_score, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New High score', new_high_score_path %>

app/views/high_scores/new.html.erb
<h1>New high_score</h1>

<%= render 'form' %>

<%= link_to 'Back', high_scores_path %>

app/views/high_scores/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_high_score_path(@high_score) %> |
<%= link_to 'Back', high_scores_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sam</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>